#76 working workaround proposal
AndreyAttr/Evo pull request #90
Opened 2017-08-08 18:52 UTC by tapy-lappy

2017-08-08 19:01 UTC, AndreyAttr requested changes
@tapy-lappy ,
Ok, I undestood the problem. I have to refuse your workaround-solution, it's quick fix and we have to find other way to resolve problem

2017-08-08 19:01 UTC, AndreyAttr commented on ClientWeb/Evolution/Components/gene.component.ts
> +        return source.map((item:Site) => new Site(item.site, item.isMutated));
Recreating of item(s) is bad approach. It means we must implement this ManuallyCast<T> interface everywhere where we need to use deep copy. Also what if there were several deep copies, as Site, Gene etc.? Then with this approach we must implement several interfaces: ManuallyCast<Site>, ManuallyCast<Gene>.

2017-08-08 19:06 UTC, tapy-lappy commented on ClientWeb/Evolution/Components/gene.component.ts
> +            this.gene.mutationSites = this.manuallyCastTo(mutationSites);   //workaround
Here we had the same workaround. I just moved it into one place - in interface

2017-08-08 19:09 UTC, tapy-lappy reviewed
So 2 places with the same quick fix code, as you can see.

2017-08-08 19:09 UTC, tapy-lappy commented on ClientWeb/Evolution/Components/gene.component.ts
> +        return source.map((item:Site) => new Site(item.site, item.isMutated));
I tried to find more acceptable way. Of couse we need to do it into ObjectHelper.deepCopy() but whatever I tried there were no way to save typings.

2017-08-08 19:09 UTC, tapy-lappy commented on ClientWeb/Evolution/Components/gene-editor.component.ts
> -        let gene = new Gene(this.gene.name, [this.currentChosenSite], this.gene.description);
Here we had this workaround.

2017-08-08 19:11 UTC, AndreyAttr commented on ClientWeb/Evolution/Components/gene.component.ts
> +            this.gene.mutationSites = this.manuallyCastTo(mutationSites);   //workaround
sad

2017-08-08 19:11 UTC, AndreyAttr commented on ClientWeb/Evolution/Components/gene-editor.component.ts
> -        let gene = new Gene(this.gene.name, [this.currentChosenSite], this.gene.description);
I see

2017-08-08 19:15 UTC, AndreyAttr commented on ClientWeb/Evolution/Components/gene.component.ts
> +        return source.map((item:Site) => new Site(item.site, item.isMutated));
@tapy-lappy,
Ok, I got it. I need to do some fixes in #76. But this approach is also unacceptable, so let it hold on till I find the way to resolve problem. Thank you so much for your investigation lad.

2017-08-11 16:04 UTC, AndreyAttr commented
@tapy-lappy , I fixed #76 to support typing(ans so computable properties & instance members as methods). Also provided there `cast()` method to get back typing(manually) from FormGroup/FormArray etc. Reactive Forms component. So #76 is not blocker for your #65 anymore. I reject this pull request. Please update from **angular** branch.

2017-08-11 16:04 UTC, closed without merging

2017-08-11 16:15 UTC, AndreyAttr commented on ClientWeb/Evolution/Components/gene.component.ts
> +        return source.map((item:Site) => new Site(item.site, item.isMutated));
> @tapy-lappy , done. You may check 2 my last commits on #76. Also found we lose typings when got back model from Reactive Form control, so now there is `cast()` method to make back-typing.
> It's workaround but I have doubts the problem
>  //Done: maybe resolved any different way:
Fortunatelly, yes. Thx you found all these stuff.